version: "3.9"
services:
  web:
    build: .
    command: uvicorn main:app --reload --host 0.0.0.0
    volumes:
      - .:/app/.
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: "postgres:15.1"
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_APP_USER
      - POSTGRES_APP_PASSWORD
      - POSTGRES_APP_DATABASE
      - POSTGRES_AUTH_USER
      - POSTGRES_AUTH_PASSWORD
      - POSTGRES_AUTH_DATABASE
    volumes:
      - db_storage:/var/lib/postgresql/data
      - ./scripts/postgres/init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    ports:
      - "5433:5432"
  author:
    image: "registry.supertokens.io/supertokens/supertokens-postgresql"
    environment:
      - POSTGRESQL_USER=${POSTGRES_AUTH_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_AUTH_PASSWORD}
      - POSTGRESQL_HOST=db
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_DATABASE_NAME=${POSTGRES_AUTH_DATABASE}
    ports:
      - "3567:3567"
    depends_on:
      - db

volumes:
  db_storage:
