#!/bin/bash
set -e;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  -- create for app
	CREATE USER ${POSTGRES_APP_USER} WITH PASSWORD '${POSTGRES_APP_PASSWORD}';
	CREATE DATABASE ${POSTGRES_APP_DATABASE};
	GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_APP_DATABASE} TO ${POSTGRES_APP_USER};
	ALTER DATABASE ${POSTGRES_APP_DATABASE} OWNER TO ${POSTGRES_APP_USER};
	-- create for auth
	CREATE USER ${POSTGRES_AUTH_USER} WITH PASSWORD '${POSTGRES_AUTH_PASSWORD}';
  CREATE DATABASE ${POSTGRES_AUTH_DATABASE};
  GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_AUTH_DATABASE} TO ${POSTGRES_AUTH_USER};
  ALTER DATABASE ${POSTGRES_AUTH_DATABASE} OWNER TO ${POSTGRES_AUTH_USER};
EOSQL
