#!/bin/bash
set -e;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  -- create for app
	CREATE USER ${POSTGRES_APP_USER} WITH PASSWORD '${POSTGRES_APP_PASSWORD}';
	CREATE DATABASE ${POSTGRES_APP_DATABASE};
	GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_APP_DATABASE} TO ${POSTGRES_APP_USER};
	ALTER DATABASE ${POSTGRES_APP_DATABASE} OWNER TO ${POSTGRES_APP_USER};
EOSQL
